name: Tests Playwright avec Notification Slack

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Installer les dépendances
      run: npm ci

    - name: Installer Playwright
      run: npx playwright install --with-deps

    - name: Exécuter les tests
      run: npx playwright test
      continue-on-error: true

    - name: Téléverser le rapport HTML
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: rapport-playwright
        path: playwright-report/

    - name: Notifier Slack
      if: always()
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Résultats des Tests Playwright",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Statut*\n${{ job.status }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Détails*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Voir les résultats>"
                  }
                ]
              }
            ]
          }